import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import dotenv from "dotenv";

dotenv.config();

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	platform: "node",
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"obsidian",
		"onnxruntime-node",
		"voyageai",
		"ollama",
		"ollama/browser",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		'.svg': 'text'
	},
	plugins: [
		    {
      name: "shim-ollama",
      setup(build) {
        build.onResolve({ filter: /^ollama/ }, (args) => ({
          path: args.path,
          namespace: "ollama-shim",
        }));
        build.onLoad({ filter: /.*/, namespace: "ollama-shim" }, () => ({
          contents: "module.exports = {};",
          loader: "js",
        }));
      },
    }
	],

	define: {
		"process.env.MODEL_PROVIDER": JSON.stringify(process.env.MODEL_PROVIDER),
		"process.env.MODEL_API_KEY": JSON.stringify(process.env.MODEL_API_KEY),
		"process.env.MODEL_ID": JSON.stringify(process.env.MODEL_ID),
		"process.env.MAX_DEPTH": JSON.stringify(process.env.MAX_DEPTH),

		"process.env.LANGSMITH_TRACING": JSON.stringify(process.env.LANGSMITH_TRACING),
		"process.env.LANGSMITH_API_KEY": JSON.stringify(process.env.LANGSMITH_API_KEY),
		"process.env.LANGSMITH_PROJECT": JSON.stringify(process.env.LANGSMITH_PROJECT),
		"process.env.LANGSMITH_ENDPOINT": JSON.stringify(process.env.LANGSMITH_ENDPOINT),

		"process.env.LANGSMITH_DISABLE_RUN_COMPRESSION": JSON.stringify(process.env.LANGSMITH_DISABLE_RUN_COMPRESSION)
	},

});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}