import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import dotenv from "dotenv";

dotenv.config();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	platform: "node",
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		'.svg': 'text'
	},

	define: {
		"process.env.MODEL_PROVIDER": JSON.stringify(process.env.MODEL_PROVIDER),
		"process.env.MODEL_API_KEY": JSON.stringify(process.env.MODEL_API_KEY),
		"process.env.MODEL_ID": JSON.stringify(process.env.MODEL_ID),
		"process.env.MAX_DEPTH": JSON.stringify(process.env.MAX_DEPTH),
		"process.env.LANGCHAIN_TRACING_V2": JSON.stringify(process.env.LANGCHAIN_TRACING_V2),
		"process.env.LANGCHAIN_API_KEY": JSON.stringify(process.env.LANGCHAIN_API_KEY),
		"process.env.LANGCHAIN_PROJECT": JSON.stringify(process.env.LANGCHAIN_PROJECT),
		"process.env.LANGCHAIN_ENDPOINT": JSON.stringify(process.env.LANGCHAIN_ENDPOINT),
		"process.env.EMAIL": JSON.stringify(process.env.EMAIL),
	}
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
