export const IDEA_MD_TEMPLATE = `> [!NOTE] How To Use
> IDEA.md is the place where you store your ideas, research questions, and other thoughts. When you have an idea for a research paper, you can create a new markdown file in the same directory and link it to this file. The more robust IDEA.md is the more robust research will be which would lead to more robust knowledge base.\n>\n`;

export const SOURCES_MD_TEMPLATE = `> [!ABSTRACT] Central Citation Source
> Here is where you would find all the cited academic papers or books which has been used throught the knowledge base. This can be used fro quick reference creation in your papers or for other purposes.  \n\n| Paper Title | DOI | Avg h-index | Avg i10-index | Avg Citedness | Year |\n|---|---|---|---|---|---|\n`;

export const getThesisHeaderTemplate = (dateString: string) => 
`---
title: Research Thesis
created: ${dateString}
---

# Research Thesis

> This document was auto-generated by Poneglyph's Idea Creation pipeline.
> Each section corresponds to one \`extract-idea\` note and its related parent notes.

---

`;

export const getThesisSectionTemplate = (index: number, primaryTitle: string, parentList: string, llmOutput: string) => 
`## ${index}. ${primaryTitle}

**Source Note**: [[${primaryTitle}]]

**Related Context**:
${parentList}

${llmOutput}

---
`;

export const LOADING_BAR_BLOCK = `<div style="text-align:center;">\n<i>Agent in progress...</i>\n<progress value="100" max="100" style="width:100%; height:6px; accent-color:var(--color-accent);"></progress>\n</div>\n`;
